/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ContactForm() {
  return (
    <section className="flex flex-col self-end mt-36 mr-20 max-w-full text-base text-white whitespace-nowrap w-[564px] max-md:mt-10 max-md:mr-2.5">
      <form className="flex flex-col items-center">
        <input
          type="text"
          className="shrink-0 self-end max-w-full bg-white rounded-2xl h-[68px] w-[275px]"
          aria-label="Name"
        />
        <textarea
          className="shrink-0 mt-14 max-w-full bg-white h-[238px] rounded-[48px] w-[541px] max-md:mt-10"
          aria-label="Message"
        ></textarea>
        <button type="submit" className="mt-16 max-md:mt-10">
          Send
        </button>
      </form>
    </section>
  );
}

export default ContactForm;
