/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SocioConnect.module.css";

function Header() {
  const navItems = ["Home", "About", "Contact", "Login", "Register"];

  return (
    <header className={styles.header}>
      <div className={styles.logo}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ba4523e045440c5ec2f842d7884f5558389fcd04caaca4b2d22beeec32358a00?placeholderIfAbsent=true&apiKey=f27a7f6532b3469a891700e4c6f63d48"
          className={styles.logoImage}
          alt="Socio Connect logo"
        />
        <h2 className={styles.logoText}>Socio Connect</h2>
      </div>
      <nav className={styles.navigation}>
        {navItems.map((item, index) => (
          <a
            key={index}
            href={`/${item.toLowerCase()}`}
            className={styles.navItem}
          >
            {item}
          </a>
        ))}
      </nav>
    </header>
  );
}

export default Header;
