/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SocioConnect.module.css";
import Header from "./Header";
import RegisterForm from "./RegisterForm";

function RegisterMain() {
  return (
    <main className={styles.container}>
      <Header />
      <section className={styles.mainContent}>
        <div className={styles.contentWrapper}>
          <div className={styles.leftColumn}>
            <div className={styles.registerSection}>
              <h1 className={styles.registerTitle}>Register</h1>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/55df2bc420d814b9bc3fe0b4c741722db43a29988c10f6977fa1033d19924890?placeholderIfAbsent=true&apiKey=f27a7f6532b3469a891700e4c6f63d48"
                className={styles.registerImage}
                alt="Registration illustration"
              />
            </div>
          </div>
          <div className={styles.rightColumn}>
            <RegisterForm />
          </div>
        </div>
      </section>
    </main>
  );
}

export default RegisterMain;
