/**
 * This code was generated by Builder.io.
 */
import React from "react";

const reasons = [
  { title: "Foster Accountability", color: "text-red-600" },
  { title: "Real-Time Updates", color: "text-white" },
  { title: "Quick and Easy Reporting", color: "text-white" },
  { title: "Transparency in Governance", color: "text-white", wide: true },
  { title: "Community Improvement", color: "text-black" },
];

function WhyUse() {
  return (
    <section className="flex flex-col px-20 pt-14 pb-32 mt-36 bg-violet-200 max-md:px-5 max-md:pb-24 max-md:mt-10 max-md:mr-0.5 max-md:max-w-full">
      <h2 className="self-center text-4xl text-black w-[362px]">
        Why to use this platform
      </h2>
      <div className="flex flex-wrap gap-5 mt-14 mb-0 w-full max-w-[1157px] max-md:mt-10 max-md:mb-2.5 max-md:max-w-full">
        {reasons.map((reason, index) => (
          <div
            key={index}
            className={`flex flex-col ${
              reason.wide ? "w-[67%]" : "w-[33%]"
            } max-md:w-full`}
          >
            <div
              className={`grow px-8 py-12 text-4xl ${reason.color} ${
                reason.wide ? "shadow-[0px_4px_4px_rgba(0,0,0,0.25)]" : ""
              } max-md:px-5`}
            >
              {reason.title}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

export default WhyUse;
