/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Logo.module.css";

const Logo = () => {
  return (
    <div className={styles.logoWrapper}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/412508ff8fccf97e89bb8a18dff43f29db4d8f73cc35c5a300729b6e36a867b7?placeholderIfAbsent=true&apiKey=f27a7f6532b3469a891700e4c6f63d48"
        alt="Socio Connect Logo"
        className={styles.logoImage}
      />
      <span className={styles.logoText}>Socio Connect</span>
    </div>
  );
};

export default Logo;
