/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";
import Logo from "../Logo/Logo";
import Navigation from "../Navigation/Navigation";

const Header = () => {
  return (
    <header className={styles.header}>
      <div className={styles.headerContent}>
        <Logo />
        <Navigation />
      </div>
    </header>
  );
};

export default Header;
