/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SocioConnect.module.css";
import Header from "./Header";
import NewsItem from "./NewsItem";

const NewsMain = () => {
  const newsItems = [
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/5aa8bdde76a89854afe3fec0fe07d112ac5018b8c42befa9909ea6c86862162b?placeholderIfAbsent=true&apiKey=f27a7f6532b3469a891700e4c6f63d48",
      content:
        "NDRF personnel saved 381 lives, evacuated 20,575 persons in recent Vijayawada floods, says Commandant \n\n26 teams from Andhra Pradesh and five other States participated in the relief and rescue operations \n\nTeams of the National Disaster Response Force (NDRF) rescued the lives of 381 persons during the recent Budameru floods in Vijayawada.",
      link: "https://www.thehindu.com/news/national/andhra-pradesh/andhra-pradesh-chief-minister-chandrababu-naidu-pegs-flood-losses-at-7600-crore/article68681303.ece",
    },
    {
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/8db5762929cee9591e06d5044130679f1e8dd4813231f56ce5beeb5778b286c4?placeholderIfAbsent=true&apiKey=f27a7f6532b3469a891700e4c6f63d48",
      secondaryImage:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/b502ffadb0a7c1fce9658b2406d4b0aa1f078a0ab72d487eb358d5b33968ab09?placeholderIfAbsent=true&apiKey=f27a7f6532b3469a891700e4c6f63d48",
      content:
        "Vijayawada railway station achieves NSG-1 status as annual revenue crosses ₹500 cr. mark \n\nVijayawada railway station generated a revenue of ₹528 crore and handled around 16.84 million passengers in 2023-24 financial year, says DRM Narendra A. Patil \n\nThe Vijayawada railway station has achieved the Non-Suburban Group- 1 (NSG-1) status, with its annual revenue crossing the Rs.500 crore mark. The Railway Board, which conducted a review recently,",
    },
  ];

  return (
    <main className={styles.container}>
      <Header />
      <h2 className={styles.latestUpdates}>Latest Updates</h2>
      <section className={styles.newsContainer}>
        <div className={styles.newsGrid}>
          {newsItems.map((item, index) => (
            <div key={index} className={styles.newsColumn}>
              <NewsItem {...item} />
            </div>
          ))}
        </div>
      </section>
    </main>
  );
};

export default NewsMain;
