/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";
import Logo from "../Logo/Logo";

const Footer = () => {
  const footerLinks = [
    {
      title: "Socio connect",
      links: ["How it works", "Features", "Demo"],
    },
    {
      title: "RESOURCES",
      links: ["Raise Issue", "Track Issue", "View Updates", "Login"],
    },
    {
      title: "ABOUT",
      links: ["Terms & Conditions", "Privacy Policy"],
    },
  ];

  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.logoColumn}>
          <Logo />
        </div>
        <div className={styles.linksColumns}>
          {footerLinks.map((column, index) => (
            <div key={index} className={styles.linkColumn}>
              <h3 className={styles.columnTitle}>{column.title}</h3>
              <ul className={styles.linkList}>
                {column.links.map((link, linkIndex) => (
                  <li key={linkIndex}>
                    <a href="#" className={styles.footerLink}>
                      {link}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
      <div className={styles.copyright}>Copyright © 2024 Socio connect</div>
    </footer>
  );
};

export default Footer;
