/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SocioConnect.module.css";
import Header from "./Header";
import IssueForm from "./IssueForm";

function IssueMain() {
  return (
    <div className={styles.container}>
      <Header />
      <main className={styles.mainContent}>
        <div className={styles.contentWrapper}>
          <div className={styles.column}>
            <div className={styles.issueHeader}>
              <h1 className={styles.issueTitle}>Raise an issue</h1>
              <p className={styles.issueSubtitle}>
                -let the government know the issue
              </p>
            </div>
          </div>
          <div className={styles.column}>
            <IssueForm />
          </div>
        </div>
      </main>
    </div>
  );
}

export default IssueMain;
