/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./WhyUse.module.css";

const WhyUse = () => {
  const reasons = [
    "Foster Accountability",
    "Real-Time Updates",
    "Quick and Easy Reporting",
    "Transparency in Governance",
    "Community Improvement",
  ];

  return (
    <section className={styles.whyUse}>
      <h2 className={styles.sectionTitle}>Why to use this platform</h2>
      <div className={styles.reasonsContainer}>
        {reasons.map((reason, index) => (
          <div key={index} className={styles.reason}>
            {reason}
          </div>
        ))}
      </div>
    </section>
  );
};

export default WhyUse;
