/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Navigation.module.css";
import { Link } from "react-router-dom";
const Navigation = () => {
  const navItems = ["Home", "About", "Contact", "Login", "Register"];

  return (
    <nav className={styles.navigation}>
      {navItems.map((item, index) => (
       <Link
       key={index}
       to={`/${item.toLowerCase()}`}
       className={styles.navItem}
     >
       {item}
     </Link>
      ))}
    </nav>
  );
};

export default Navigation;
